---
- name: config_stackstorm | configuring stackstorm
  template:
    src: "etc/st2/st2.conf.j2"
    dest: "/etc/st2/st2.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart stackstorm
    - reload stackstorm
