---
- name: config_db | Granting DB Permissions For User {{ stackstorm_db_info.user }}
  become: true
  become_user: "postgres"
  vars:
    ansible_ssh_pipelining: true
  postgresql_user:
    name: "{{ stackstorm_db_info.user }}"
    password: "{{ stackstorm_db_info.password }}"
    role_attr_flags: "CREATEDB"
    encrypted: yes
    state: "present"

- name: config_db | Creating DB {{ stackstorm_db_info.db }}
  become: true
  become_user: "postgres"
  vars:
    ansible_ssh_pipelining: true
  postgresql_db:
    name: "{{ stackstorm_db_info.db }}"
    owner: "{{ stackstorm_db_info.user }}"
    state: "present"

- name: config_db | Checking If DB {{ stackstorm_db_info.db }} Has Been Populated
  stat:
    path: "/etc/mistral/.db_populated"
  register: "mistral_db_populated_check"

- name: config_db | Populating DB {{ stackstorm_db_info.db }}
  command: "/opt/stackstorm/mistral/bin/mistral-db-manage --config-file /etc/mistral/mistral.conf upgrade head"
  register: "mistral_db_populated"
  become: true
  when: not mistral_db_populated_check.stat.exists

- name: config_db | Registering Mistral Actions
  command: "/opt/stackstorm/mistral/bin/mistral-db-manage --config-file /etc/mistral/mistral.conf populate"
  become: true
  when: mistral_db_populated.changed

- name: config_db | Marking DB {{ stackstorm_db_info.db }} As Populated
  file:
    path: "/etc/mistral/.db_populated"
    state: touch
  become: true
  when: mistral_db_populated.changed
