---
- name: debian | Installing CA-Certs
  apt:
    name: ca-certificates
    state: present
  become: true

- name: debian | Adding Stackstorm Repo Key
  apt_key:
    url: "{{ stackstorm_debian_repo_info.repo_key }}"
    state: present
  become: true

- name: debian | Installing apt-transport-https
  apt:
    name: apt-transport-https
    state: present
  become: true

- name: debian | Adding Stackstorm Repos
  apt_repository:
    repo: "{{ item }}"
    state: present
  become: true
  with_items: "{{ stackstorm_debian_repo_info.repos }}"

- name: debian | Installing Stackstorm Packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  become: true
  with_items: "{{ stackstorm_debian_packages }}"
