---
- name: config_php | installing PHP-{{ nginx_php_ver }}
  apk:
    name: "{{ item }}"
    state: "present"
  become: true
  with_items:
    - 'php{{ nginx_php_ver }}'
    - 'php{{ nginx_php_ver }}-cli'
    - 'php{{ nginx_php_ver }}-fpm'
  when: >
        ansible_os_family == "Alpine"

- name: config_php | installing PHP-{{ nginx_php_ver }}
  apt:
    name: "{{ item }}"
    state: "present"
  become: true
  with_items:
    - 'php{{ nginx_php_ver }}'
    - 'php{{ nginx_php_ver }}-cli'
    - 'php{{ nginx_php_ver }}-fpm'
  when: >
        ansible_os_family == "Debian"

- name: config_php | configuring php.ini
  template:
    src: "{{ nginx_php_path }}/{{ item }}.j2"
    dest: "/{{ nginx_php_path }}/{{ item }}"
    owner: "root"
    group: "root"
    mode: 0644
  become: true
  notify:
    - "restart nginx"
    - "restart php{{ nginx_php_ver }}-fpm"
  with_items:
    - 'fpm/php.ini'
    - 'cli/php.ini'
  when: >
        ansible_os_family == "Debian"
