---
# handlers file for ansible-stackstorm
- name: reload stackstorm
  command: "st2ctl reload"
  become: true

- name: restart nginx
  service:
    name: "nginx"
    state: restarted
  become: true

- name: restart st2api
  command: "st2ctl restart-component st2api"
  become: true

- name: restart stackstorm
  command: "st2ctl restart"
  become: true

- name: start stackstorm
  command: "st2ctl start"
  become: true
