---
# handlers file for ansible-nginx
- name: "restart nginx"
  service:
    name: "nginx"
    state: "restarted"

- name: "restart php{{ nginx_php_ver }}-fpm"
  service:
    name: "php{{ nginx_php_ver }}-fpm"
    state: "restarted"
