---
- name: debian | Installing Postgresql Pre-Reqs
  apt:
    name: "{{ item }}"
    state: "present"
  become: true
  with_items: "{{ postgresql_debian_pre_reqs }}"

- name: debian | Installing Postgresql Python Modules
  pip:
    name: "{{ item }}"
    state: "present"
  become: true
  with_items:
    - 'psycopg2'

- name: debian | Adding Postgresql Repo Key
  apt_key:
    url: "{{ postgresql_debian_repo_info['key'] }}"
    state: "present"
  become: true

- name: debian | Adding Postgresql Repo
  apt_repository:
    repo: "{{ postgresql_debian_repo_info['repo'] }}"
    state: "present"
  become: true

- name: debian | Installing Postgresql
  apt:
    name: "{{ item }}"
    state: "present"
  become: true
  with_items:
    - 'postgresql-{{ postgresql_version }}-debversion'
    - 'postgresql-client-{{ postgresql_version }}'
    - 'postgresql-contrib-{{ postgresql_version }}'
    - 'postgresql-plpython-{{ postgresql_version }}'
    - 'postgresql-{{ postgresql_version }}'
