---
- name: redhat | installing epel repo (RedHat)
  yum:
    name: "epel-release"
    state: present
  when: ansible_distribution != "Fedora"

- name: redhat | installing dependencies
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - 'dnf'
    - 'python-devel'
    - 'python-dnf'
    - 'python-pip'
  when: ansible_distribution != "Fedora"

- name: redhat | installing nginx
  dnf:
    name: "nginx"
    state: present

- name: redhat | ensuring nginx is started and enabled on boot
  service:
    name: "nginx"
    state: started
    enabled: yes
